### ISSUE TITLE
load unpacked fails with chrome

### ISSUE THREAD

**Issue by skewballfox** [rimutaka/spotify-playlist-builder#1]
Hey awesome guide/project! I'm using it as a reference point while working on another extension. I ran into an issue where chrome couldn't load the service worker, and it seemed to be because background.js needs to be in the root directory.

Out of curiosity I cloned the project locally and performed the following steps:
1. chmodded and ran build.sh
2. unzipped the chrome.zip into chrome-out
3. attempted to load unpacked

I got the following error:

File        ~/Workspace/spotify-playlist-builder/extension

Error     Could not load icon 'assets/toolbar_icon_32.png' specified in 'action'.

               Could not load manifest.

~~I suspect after whatever caused that was fixed, it would also throw an error because it can't load the background.js.~~

Edit: so I'm an idiot, or at least the people I were referencing were(or both). I managed to get my extension to work with the background js in a sub directory.

**Comment by rimutaka** [comment]
@skewballfox , you can point Chrome at `extension` folder without using the zip archive. It should work as long as the folder contains the right manifest file. Hope my extension helped you get up to speed quicker. Any feedback or suggestions on improving the docs or the code are welcome.

**Comment by skewballfox** [comment]
> you can point Chrome at extension folder without using the zip archive

I know, I just figured it would be easier to explain the steps to reproduce this way. I did actually try both as a sort of sanity check prior to creating this issue

The extension is currently failing to load in either case. Here's a copy of the error message.
![image](https://github.com/rimutaka/spotify-playlist-builder/assets/29311431/b8749eb0-50ea-43ad-9d17-e8d8a8854498)

 Do you know how to get logs for load unpacked? So far, the error messages sometimes seem opaque at best and misleading at worst.

**Comment by rimutaka** [comment]
@skewballfox , sorry, my bad. The 32px icon was missing, exactly as the error message suggested.
I updated the repo and it successfully loaded in Chrome.

Can you pull and try again?

![image](https://github.com/rimutaka/spotify-playlist-builder/assets/5926028/35d2fadd-81fb-4c57-936c-979d10b82575)

**Comment by skewballfox** [comment]
I can't believe I missed that. Pulled and checked. It works now
